name: Build VESC Harmony32 Firmware

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup ESP-IDF
      - name: Setup ESP-IDF
        uses: espressif/setup-esp-idf@v3
        with:
          version: 'v5.1'

      # 3. Install STM32 toolchain
      - name: Install STM32 toolchain
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi make

      # 4. Set hwconf
      - name: Set hwconf
        run: |
          cp -r main/hwconf/vesc/vbms32 main/hwconf/current

      # 5. Build firmware
      - name: Build firmware
        run: |
          cd main
          idf.py set-target esp32c3
          idf.py build

      # 6. Upload binaries
      - name: Upload firmware binaries
        uses: actions/upload-artifact@v4
        with:
          name: vesc_harmony32_firmware
          path: main/build/
